<a href="https://colab.research.google.com/github/saisohanallam/ML_LAB_2026-27/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
list1 = [2, 4, 6, 8]


array1 = np.array(list1)

print(array1)

[2 4 6 8]


In [6]:
array1 = np.array([2, 4, 6, 8])
print(array1)

[2 4 6 8]


In [7]:
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
arr = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(arr)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [20]:
print(arr.dtype)

int64


In [21]:
print(arr.ndim)

3


In [22]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])
print(array1.shape)

(2, 3)


In [23]:
array1 = np.array([6, 7, 8, 10, 13])
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)
print(array1.itemsize)
print(array2.itemsize)

8
4


In [24]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7bd6bc6ca440>
Data of array2 is:  <memory at 0x7bd6bc469080>


In [25]:
array1 = np.array([1, 3, 5, 7, 9])
print(array1[0])
print(array1[2])
print(array1[4])

1
5
9


In [26]:
array1[1]=10
print(array1)


[ 1 10  5  7  9]


In [27]:
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)


4th Element at 2nd Row: 15
2nd Element at First Row: 3


In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
median = np.median(array1)

print(median)

In [28]:
marks = np.array([76, 78, 81, 66, 85])
mean_marks = np.mean(marks)
print(mean_marks)


77.2


In [29]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.std(marks)
print(std_marks)

6.368673331236263


In [30]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.percentile(marks,50)
print(std_marks)


78.0


In [31]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.min(marks)
print(std_marks)

66


In [ ]:
marks = np.array([76, 78, 81, 66, 85])
std_marks = np.max(marks)
print(std_marks)
